# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ds_eqp_1 <- function(y, lambda = 1) {
  .Call('dslice_ds_eqp_1', y, lambda, PACKAGE = 'dslice')
}

ds_1 <- function(y, lambda = 1, alpha = 1) {
  .Call('dslice_ds_1', y, lambda, alpha, PACKAGE = 'dslice')
}

ds_eqp_k <- function(x, dim, lambda = 1) {
  .Call('dslice_ds_eqp_k', x, dim, lambda, PACKAGE = 'dslice')
}

ds_k <- function(x, dim, lambda = 1) {
  .Call('dslice_ds_k', x, dim, lambda, PACKAGE = 'dslice')
}

dslice_eqp_k <- function(x, dim, lambda = 1) {
  .Call('dslice_dslice_eqp_k', x, dim, lambda, PACKAGE = 'dslice')
}

dslice_k <- function(x, dim, lambda = 1) {
  .Call('dslice_dslice_k', x, dim, lambda, PACKAGE = 'dslice')
}
